-- MySQL Workbench Synchronization
-- Generated: 2025-03-22 09:10
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Breno Mayder

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `biblioteca`.`autor` 
ADD COLUMN `status` TINYINT(1) NOT NULL DEFAULT 1 AFTER `data_nascimento`;

ALTER TABLE `biblioteca`.`editora` 
CHANGE COLUMN `status` `status` TINYINT(1) NOT NULL DEFAULT 1 ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
